/* 
INSERTO LOS DATOS DE LA TABLA MAESTRA 
A NUESTRAS NUEVAS TABLAS
*/

--1 
INSERT INTO Provincia (PROVINCIA_NOMBRE)
SELECT DISTINCT CLIENTE_PROVINCIA 
FROM gd_esquema.Maestra 

--2 
INSERT INTO Localidad (PROVINCIA_ID, LOCALIDAD_NOMBRE)
SELECT P.PROVINCIA_ID, M.CLIENTE_LOCALIDAD
FROM gd_esquema.Maestra M
INNER JOIN Provincia P ON M.CLIENTE_PROVINCIA = P.PROVINCIA_NOMBRE;

INSERT INTO Localidad (PROVINCIA_ID, LOCALIDAD_NOMBRE)
SELECT P.PROVINCIA_ID, M.SUPER_LOCALIDAD
FROM gd_esquema.Maestra M
INNER JOIN Provincia P ON M.CLIENTE_PROVINCIA = P.PROVINCIA_NOMBRE

--3
INSERT INTO Domicilio (LOCALIDAD_ID, DIRECCION, ALTURA, PISO, DEPARTAMENTO)
SELECT L.LOCALIDAD_ID,
       SUBSTRING(M.CLIENTE_DOMICILIO, 1, LEN(M.CLIENTE_DOMICILIO) - CHARINDEX(' ', REVERSE(M.CLIENTE_DOMICILIO))) AS DIRECCION,
       RIGHT(M.CLIENTE_DOMICILIO, CHARINDEX(' ', REVERSE(M.CLIENTE_DOMICILIO)) - 1) AS ALTURA,
       NULL AS PISO,
       NULL AS DEPARTAMENTO
FROM gd_esquema.Maestra M
INNER JOIN Localidad L ON M.CLIENTE_LOCALIDAD = L.LOCALIDAD_NOMBRE;

INSERT INTO Localidad (LOCALIDAD_NOMBRE) 
VALUES ('Colonia La Chispa')
INSERT INTO Domicilio (DIRECCION, ALTURA)
VALUES ('Avenida Figueroa Alcorta',1866)

SELECT DISTINCT SUPER_DOMICILIO, SUPER_LOCALIDAD FROM gd_esquema.Maestra

--4
INSERT INTO Cliente (
    CLIENTE_NOMBRE, CLIENTE_APELLIDO, CLIENTE_DNI, CLIENTE_FECHA_REGISTRO,
    CLIENTE_FECHA_NACIMIENTO, CLIENTE_MAIL, CLIENTE_TELEFONO,
    DOMICILIO_ID 
)
SELECT DISTINCT
    CLIENTE_NOMBRE, CLIENTE_APELLIDO, CLIENTE_DNI, CLIENTE_FECHA_REGISTRO,
    CLIENTE_FECHA_NACIMIENTO, CLIENTE_MAIL, CLIENTE_TELEFONO,
    D.DOMICILIO_ID 
FROM gd_esquema.Maestra M
INNER JOIN Domicilio D ON 
M.CLIENTE_DOMICILIO = D.DIRECCION + ' ' + CAST(D.ALTURA AS NVARCHAR(50));

--5 
INSERT INTO Marca (
MARCA_NOMBRE, MARCA_DECRIPCION
)
SELECT DISTINCT PRODUCTO_MARCA, null FROM gd_esquema.Maestra

--6
INSERT INTO Subcategoria (
	SUBCATEGORIA_NOMBRE, SUBCATEGORIA_DESCRIPCION
) 
SELECT DISTINCT PRODUCTO_SUB_CATEGORIA, null FROM gd_esquema.Maestra

--7
INSERT INTO Categoria (
CATEGORIA_NOMBRE, SUBCATEGORIA_ID
)
SELECT DISTINCT PRODUCTO_CATEGORIA, S.SUBCATEGORIA_ID
FROM gd_esquema.Maestra M 
INNER JOIN Subcategoria S ON M.PRODUCTO_SUB_CATEGORIA = S.SUBCATEGORIA_NOMBRE

--8
INSERT INTO Producto(
PRODUCTO_NOMBRE, PRODUCTO_DESCRIPCION, PRODUCTO_PRECIO, MARCA_ID, CATEGORIA_ID
)
SELECT DISTINCT PRODUCTO_NOMBRE, PRODUCTO_DESCRIPCION, PRODUCTO_PRECIO, 
Ma.MARCA_ID, C.CATEGORIA_ID
FROM gd_esquema.Maestra M
INNER JOIN Categoria C ON M.PRODUCTO_CATEGORIA = C.CATEGORIA_NOMBRE
INNER JOIN Marca Ma ON M.PRODUCTO_MARCA = Ma.MARCA_NOMBRE

--9 SUPERMERCADO

/*
INSERT INTO #Tabla_Temporal (
SUPER_NOMBRE, SUPER_RAZON_SOC, SUPER_CUIT, SUPER_IIBB,
SUPER_FECHA_INI_ACTIVIDAD, DOMICILIO_ID
)
SELECT SUPER_NOMBRE, SUPER_RAZON_SOC, SUPER_CUIT, SUPER_IIBB,
SUPER_FECHA_INI_ACTIVIDAD, D.DOMICILIO_ID
FROM gd_esquema.Maestra M 
INNER JOIN Domicilio D ON 
M.SUPER_DOMICILIO = D.DIRECCION + ' ' + CAST(D.ALTURA AS NVARCHAR(50))
*/


SELECT SUPER_DOMICILIO FROM gd_esquema.Maestra

--10 SUCURSAL

--11 EMPLEADO

--12
INSERT INTO TipoCaja (
CAJA_NOMBRE, CAJA_DESCRIPCION
)
SELECT DISTINCT CAJA_TIPO, null
FROM gd_esquema.Maestra

--13
INSERT INTO Caja (
CAJA_NUMERO, CAJA_TIPO_ID
)
SELECT DISTINCT CAJA_NUMERO, T.CAJA_TIPO_ID 
FROM gd_esquema.Maestra M
INNER JOIN TipoCaja T ON M.CAJA_TIPO = T.CAJA_NOMBRE

--14 
-- ...

SELECT * INTO #Tabla_Temporal FROM CAJA
SELECT * FROM #Tabla_Temporal
DROP TABLE #Tabla_Temporal