CREATE TABLE Supermercado (
    SUPER_ID INT PRIMARY KEY IDENTITY,
    SUPER_NOMBRE NVARCHAR(255) NOT NULL,
    SUPER_RAZON_SOC NVARCHAR(255) NOT NULL,
    SUPER_CUIT NVARCHAR(20) NOT NULL,
    SUPER_IIBB NVARCHAR(20) NOT NULL,
    SUPER_DOMICILIO NVARCHAR(255),
    SUPER_FECHA_INI_ACTIVIDAD DATETIME,
    SUPER_CONDICION_FISCAL NVARCHAR(255)
);

CREATE TABLE Sucursal (
    SUCURSAL_ID INT PRIMARY KEY IDENTITY,
    SUPER_ID INT FOREIGN KEY REFERENCES Supermercado(SUPER_ID),
    SUCURSAL_NOMBRE NVARCHAR(255) NOT NULL,
    SUCURSAL_DIRECCION NVARCHAR(255),
    SUCURSAL_LOCALIDAD NVARCHAR(255),
    SUCURSAL_PROVINCIA NVARCHAR(255)
);

CREATE TABLE Empleado (
    EMPLEADO_ID INT PRIMARY KEY IDENTITY,
    SUCURSAL_ID INT FOREIGN KEY REFERENCES Sucursal(SUCURSAL_ID),
    EMPLEADO_NOMBRE NVARCHAR(255) NOT NULL,
    EMPLEADO_APELLIDO NVARCHAR(255) NOT NULL,
    EMPLEADO_DNI DECIMAL(18, 0) NOT NULL,
    EMPLEADO_FECHA_REGISTRO DATETIME,
    EMPLEADO_TELEFONO NVARCHAR(20)
);

CREATE TABLE Producto (
    PRODUCTO_ID INT PRIMARY KEY IDENTITY,
    PRODUCTO_NOMBRE NVARCHAR(255) NOT NULL,
    PRODUCTO_CATEGORIA NVARCHAR(255),
    PRODUCTO_SUBCATEGORIA NVARCHAR(255),
    PRODUCTO_PRECIO DECIMAL(18, 2)
);

CREATE TABLE Ticket (
    TICKET_ID INT PRIMARY KEY IDENTITY,
    SUCURSAL_ID INT FOREIGN KEY REFERENCES Sucursal(SUCURSAL_ID),
    EMPLEADO_ID INT FOREIGN KEY REFERENCES Empleado(EMPLEADO_ID),
    TICKET_NUMERO DECIMAL(18, 0) NOT NULL,
    TICKET_FECHA_HORA DATETIME NOT NULL,
    TICKET_TIPO_COMPROBANTE NVARCHAR(255),
    TICKET_SUBTOTAL_PRODUCTOS DECIMAL(18, 2),
    TICKET_TOTAL_DESCUENTO_APLICADO DECIMAL(18, 2),
    TICKET_TOTAL_DESCUENTO_APLICADO_MP DECIMAL(18, 2),
    TICKET_TOTAL_ENVIO DECIMAL(18, 2),
    TICKET_TOTAL_TICKET DECIMAL(18, 2)
);

CREATE TABLE DetalleTicket (
    DETALLE_TICKET_ID INT PRIMARY KEY IDENTITY,
    TICKET_ID INT FOREIGN KEY REFERENCES Ticket(TICKET_ID),
    PRODUCTO_ID INT FOREIGN KEY REFERENCES Producto(PRODUCTO_ID),
    CANTIDAD INT,
    PRECIO_UNITARIO DECIMAL(18, 2),
    DESCUENTO_APLICADO DECIMAL(18, 2),
    TOTAL_PRODUCTO DECIMAL(18, 2)
);

CREATE TABLE MedioDePago (
    MEDIO_PAGO_ID INT PRIMARY KEY IDENTITY,
    MEDIO_PAGO_DESCRIPCION NVARCHAR(255) NOT NULL
);


CREATE TABLE Pago (
    PAGO_ID INT PRIMARY KEY IDENTITY,
    TICKET_ID INT FOREIGN KEY REFERENCES Ticket(TICKET_ID),
    FECHA_PAGO DATETIME NOT NULL,
    IMPORTE DECIMAL(18, 2) NOT NULL
);

CREATE TABLE DetallePago (
    DETALLE_PAGO_ID INT PRIMARY KEY IDENTITY,
    PAGO_ID INT FOREIGN KEY REFERENCES Pago(PAGO_ID),
    MEDIO_PAGO_ID INT FOREIGN KEY REFERENCES MedioDePago(MEDIO_PAGO_ID),
    CLIENTE_NOMBRE NVARCHAR(255),
    CLIENTE_DNI DECIMAL(18, 0),
    NUMERO_TARJETA NVARCHAR(20),
    FECHA_VENCIMIENTO_TARJETA DATETIME,
    CUOTAS INT
);

CREATE TABLE PromocionProducto (
    PROMOCION_ID INT PRIMARY KEY IDENTITY,
    DESCRIPCION NVARCHAR(255) NOT NULL,
    FECHA_INICIO DATETIME,
    FECHA_FIN DATETIME,
    PRODUCTO_ID INT FOREIGN KEY REFERENCES Producto(PRODUCTO_ID),
    DESCUENTO_PORCENTAJE DECIMAL(18, 2),
    CANTIDAD_APLICABLE_REGLA INT,
    CANTIDAD_APLICABLE_DESCUENTO INT,
    CANTIDAD_MAXIMA INT,
    MISMA_MARCA BIT,
    MISMO_PRODUCTO BIT
);

CREATE TABLE DescuentoMedioPago (
    DESCUENTO_ID INT PRIMARY KEY IDENTITY,
    DESCRIPCION NVARCHAR(255) NOT NULL,
    MEDIO_PAGO_ID INT FOREIGN KEY REFERENCES MedioDePago(MEDIO_PAGO_ID),
    FECHA_INICIO DATETIME,
    FECHA_FIN DATETIME,
    DESCUENTO_PORCENTAJE DECIMAL(18, 2),
    TOPE_DESCUENTO DECIMAL(18, 2)
);

CREATE TABLE Promocion_x_Producto (
    PRODUCTO_ID INT FOREIGN KEY REFERENCES Producto(PRODUCTO_ID),
    PROMOCION_ID INT FOREIGN KEY REFERENCES PromocionProducto(PROMOCION_ID),
    PRIMARY KEY (PRODUCTO_ID, PROMOCION_ID)
);

CREATE TABLE Regla (
    REGLA_ID INT PRIMARY KEY IDENTITY,
    REGLA_DESCRIPCION NVARCHAR(255) NOT NULL,
    REGLA_DESCUENTO_PORCENTAJE DECIMAL(18, 2) NOT NULL,
    REGLA_CANTIDAD_APLICABLE_REGLA INT NOT NULL,
    REGLA_CANTIDAD_APLICABLE_DESCUENTO INT NOT NULL,
    REGLA_CANTIDAD_MAXIMA INT NOT NULL,
    REGLA_MISMA_MARCA BIT NOT NULL,
    REGLA_MISMO_PRODUCTO BIT NOT NULL
);

TABLE CREATE Promocion_x_Regla (
	REGLA_ID INT FOREIGN KEY REFERENCES Regla(REGLA_ID),
	PROMOCION_ID INT FOREIGN KEY REFERENCES Regla(PROMOCION_ID)
	PRIMARY KEY (REGLA_ID, PROMOCION_ID)
)

/* TABLAS CREADAS HASTA EL MOMENTO
	Supermercado
	Sucursal
	Empleado
	Producto
	Ticket
	DetalleTicket
	Pago
	DetallePago
	MedioDePago
	PromocionProducto
	DescuentoMedioPago
	Promocion_x_Producto
	Regla
	Promocion_x_Regla
*/


/* DROPS DE TABLAS PARA TESTEAR*/
DROP TABLE IF EXISTS Promocion_x_Regla;
DROP TABLE IF EXISTS Promocion_x_Producto;
DROP TABLE IF EXISTS DescuentoMedioPago;
DROP TABLE IF EXISTS PromocionProducto;
DROP TABLE IF EXISTS DetallePago;
DROP TABLE IF EXISTS Pago;
DROP TABLE IF EXISTS DetalleTicket;
DROP TABLE IF EXISTS Ticket;
DROP TABLE IF EXISTS Producto;
DROP TABLE IF EXISTS Empleado;
DROP TABLE IF EXISTS Sucursal;
DROP TABLE IF EXISTS Supermercado;
DROP TABLE IF EXISTS Reglas;
DROP TABLE IF EXISTS MedioDePago;
DROP TABLE IF EXISTS TipoMedioPago;
